-- Create role dba
CREATE ROLE "dba"  WITH LOGIN PASSWORD 'dba-admin' CREATEDB CREATEROLE;

-- Permissão para alterar qualquer role
GRANT ALL PRIVILEGES ON DATABASE empresa_de_transportes TO dba WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON TABLE cliente TO dba WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON TABLE disponibilidade TO dba WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON TABLE compra TO dba WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON TABLE veiculos TO dba WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON TABLE rotas TO dba WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON TABLE horario TO dba WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON TABLE cidade TO dba WITH GRANT OPTION;




