CREATE ROLE "Anonimo";
GRANT SELECT ON TABLE disponibilidade TO "Anonimo";

CREATE ROLE "Gerente" WITH LOGIN PASSWORD 'gerente0001';
GRANT SELECT, UPDATE ON TABLE cliente TO "Gerente" WITH GRANT OPTION;
GRANT SELECT, UPDATE ON TABLE disponibilidade TO "Gerente" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE compra TO "Gerente" WITH GRANT OPTION;
GRANT SELECT, UPDATE ON TABLE veiculos TO "Gerente" WITH GRANT OPTION;
GRANT SELECT, UPDATE ON TABLE rotas TO "Gerente" WITH GRANT OPTION;
GRANT SELECT, UPDATE ON TABLE horario TO "Gerente" WITH GRANT OPTION;
GRANT SELECT ON TABLE cidade TO "Gerente" WITH GRANT OPTION;

CREATE ROLE "Cliente" WITH LOGIN PASSWORD 'cliente2000';
GRANT SELECT, UPDATE ON TABLE cliente TO "Cliente";
GRANT SELECT ON TABLE disponibilidade TO "Cliente";
GRANT SELECT, INSERT ON TABLE compra TO "Cliente";
GRANT SELECT ON TABLE rotas TO "Cliente";
GRANT SELECT ON TABLE cidade TO "Cliente";

CREATE ROLE "Vendedor"  WITH LOGIN PASSWORD 'vendedor-0002';
CREATE ROLE "Motorista"  WITH LOGIN PASSWORD 'motorista-0003';
